backend:
  name: github
  repo: mrtgns/ersah-kurumsal
  branch: main
  base_url: https://ersah-kurumsal.vercel.app # Buranın sonuna "/" koyma!
  auth_endpoint: api/auth
  local_backend: true
media_folder: "public/img/urunler"
public_folder: "/img/urunler"

collections:
  - name: "urunler"
    label: "Ürünler"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Ürün Adı", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Kategori", name: "category", widget: "select", options: ["is-montlari", "is-polarlari"] }
      - { label: "Ürün Görseli", name: "image", widget: "image" }
      - { label: "Açıklama", name: "description", widget: "text" }
      - { label: "Tarih", name: "date", widget: "datetime" }